# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xiaozl/文档/空中机器人/光流

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xiaozl/文档/空中机器人/光流

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xiaozl/文档/空中机器人/光流/CMakeFiles /home/xiaozl/文档/空中机器人/光流/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xiaozl/文档/空中机器人/光流/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named blueflow

# Build rule for target.
blueflow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blueflow
.PHONY : blueflow

# fast build rule for target.
blueflow/fast:
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/build
.PHONY : blueflow/fast

#=============================================================================
# Target rules for targets named px4flow

# Build rule for target.
px4flow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 px4flow
.PHONY : px4flow

# fast build rule for target.
px4flow/fast:
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/build
.PHONY : px4flow/fast

#=============================================================================
# Target rules for targets named fastflow

# Build rule for target.
fastflow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fastflow
.PHONY : fastflow

# fast build rule for target.
fastflow/fast:
	$(MAKE) -f CMakeFiles/fastflow.dir/build.make CMakeFiles/fastflow.dir/build
.PHONY : fastflow/fast

FastFlow.o: FastFlow.cpp.o

.PHONY : FastFlow.o

# target to build an object file
FastFlow.cpp.o:
	$(MAKE) -f CMakeFiles/fastflow.dir/build.make CMakeFiles/fastflow.dir/FastFlow.cpp.o
.PHONY : FastFlow.cpp.o

FastFlow.i: FastFlow.cpp.i

.PHONY : FastFlow.i

# target to preprocess a source file
FastFlow.cpp.i:
	$(MAKE) -f CMakeFiles/fastflow.dir/build.make CMakeFiles/fastflow.dir/FastFlow.cpp.i
.PHONY : FastFlow.cpp.i

FastFlow.s: FastFlow.cpp.s

.PHONY : FastFlow.s

# target to generate assembly for a file
FastFlow.cpp.s:
	$(MAKE) -f CMakeFiles/fastflow.dir/build.make CMakeFiles/fastflow.dir/FastFlow.cpp.s
.PHONY : FastFlow.cpp.s

blueflow.o: blueflow.cpp.o

.PHONY : blueflow.o

# target to build an object file
blueflow.cpp.o:
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/blueflow.cpp.o
.PHONY : blueflow.cpp.o

blueflow.i: blueflow.cpp.i

.PHONY : blueflow.i

# target to preprocess a source file
blueflow.cpp.i:
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/blueflow.cpp.i
.PHONY : blueflow.cpp.i

blueflow.s: blueflow.cpp.s

.PHONY : blueflow.s

# target to generate assembly for a file
blueflow.cpp.s:
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/blueflow.cpp.s
.PHONY : blueflow.cpp.s

bluefox/flow.o: bluefox/flow.cpp.o

.PHONY : bluefox/flow.o

# target to build an object file
bluefox/flow.cpp.o:
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/bluefox/flow.cpp.o
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/bluefox/flow.cpp.o
	$(MAKE) -f CMakeFiles/fastflow.dir/build.make CMakeFiles/fastflow.dir/bluefox/flow.cpp.o
.PHONY : bluefox/flow.cpp.o

bluefox/flow.i: bluefox/flow.cpp.i

.PHONY : bluefox/flow.i

# target to preprocess a source file
bluefox/flow.cpp.i:
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/bluefox/flow.cpp.i
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/bluefox/flow.cpp.i
	$(MAKE) -f CMakeFiles/fastflow.dir/build.make CMakeFiles/fastflow.dir/bluefox/flow.cpp.i
.PHONY : bluefox/flow.cpp.i

bluefox/flow.s: bluefox/flow.cpp.s

.PHONY : bluefox/flow.s

# target to generate assembly for a file
bluefox/flow.cpp.s:
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/bluefox/flow.cpp.s
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/bluefox/flow.cpp.s
	$(MAKE) -f CMakeFiles/fastflow.dir/build.make CMakeFiles/fastflow.dir/bluefox/flow.cpp.s
.PHONY : bluefox/flow.cpp.s

px4flow.o: px4flow.cpp.o

.PHONY : px4flow.o

# target to build an object file
px4flow.cpp.o:
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/px4flow.cpp.o
.PHONY : px4flow.cpp.o

px4flow.i: px4flow.cpp.i

.PHONY : px4flow.i

# target to preprocess a source file
px4flow.cpp.i:
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/px4flow.cpp.i
.PHONY : px4flow.cpp.i

px4flow.s: px4flow.cpp.s

.PHONY : px4flow.s

# target to generate assembly for a file
px4flow.cpp.s:
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/px4flow.cpp.s
.PHONY : px4flow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... blueflow"
	@echo "... rebuild_cache"
	@echo "... px4flow"
	@echo "... fastflow"
	@echo "... FastFlow.o"
	@echo "... FastFlow.i"
	@echo "... FastFlow.s"
	@echo "... blueflow.o"
	@echo "... blueflow.i"
	@echo "... blueflow.s"
	@echo "... bluefox/flow.o"
	@echo "... bluefox/flow.i"
	@echo "... bluefox/flow.s"
	@echo "... px4flow.o"
	@echo "... px4flow.i"
	@echo "... px4flow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

